package com.example.MyBookShopApp.entity;

import com.fasterxml.jackson.annotation.JsonIgnore;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import javax.persistence.*;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;


@Entity
@Getter
@Setter
@NoArgsConstructor
@Table(name = "author")
@ApiModel(description = "Data model of author entity")
public class Author {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @ApiModelProperty(value = "Author id generated by DB", required = true, example = "1", position = 1)
    private Integer id;

    private String photo;

    @Column(nullable = false)
    @ApiModelProperty(required = true)
    private String slug;

    @Column(nullable = false)
    @ApiModelProperty(value = "Name of author", required = true, position = 2)
    private String name;

    @Column(columnDefinition="TEXT")
    @ApiModelProperty(value = "Author biography", position = 3)
    private String description;

    @OneToMany(mappedBy = "author")
    @JsonIgnore
    private List<AuthorBooks> bookList = new ArrayList<>();

    public Author(String slug, String name) {
        this.slug = slug;
        this.name = name;
    }

    @JsonIgnore
    public List<Book> getBooks() {
        return this.bookList.stream().map(AuthorBooks::getBook).collect(Collectors.toList());
    }

}
