package com.example.MyBookShopApp.entity;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import javax.persistence.*;
import java.util.*;
import java.util.stream.Collectors;


@Entity
@Getter
@Setter
@NoArgsConstructor
@Table(name = "book")
@ApiModel(description = "Data model of book entity")
public class Book {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @ApiModelProperty(value = "Book id generated by DB", example = "1", required = true, position = 1)
    private Integer id;

    @Column(columnDefinition = "TIMESTAMP WITHOUT TIME ZONE", nullable = false)
    @ApiModelProperty(value = "Publication date", required = true, position = 2)
    private Date pubDate;

    @Column(columnDefinition="SMALLINT", nullable = false)
    @ApiModelProperty(example = "0", required = true)
    private Integer isBestseller;

    @Column(nullable = false)
    @ApiModelProperty(required = true)
    private String slug;

    @Column(nullable = false)
    @ApiModelProperty(required = true)
    private String title;

    private String image;

    @Column(columnDefinition="TEXT")
    private String description;

    @Column(nullable = false)
    @ApiModelProperty(example = "100", required = true)
    private Integer price;

    @Column(columnDefinition="smallint default 0", nullable = false)
    @ApiModelProperty(example = "50", required = true)
    private Integer discount;

    @JsonIgnore
    @OneToMany(mappedBy = "book", cascade = CascadeType.REMOVE)
    private List<AuthorBooks> authorList = new ArrayList<>();

    @JsonIgnore
    @ManyToMany
    @JoinTable(name = "book2genre", joinColumns = @JoinColumn(name = "book_id"), inverseJoinColumns = @JoinColumn(name = "genre_id"))
    private List<Genre> genresList = new ArrayList<>();

    @JsonIgnore
    @ManyToMany
    @JoinTable(name = "book2tag", joinColumns = @JoinColumn(name = "book_id"), inverseJoinColumns = @JoinColumn(name = "tag_id"))
    private List<Tag> tagsList = new ArrayList<>();

    @JsonIgnore
    @OneToMany(mappedBy = "book")
    private List<BookFile> bookFileList = new ArrayList<>();

    @JsonProperty("discountPrice")
    public Integer getDiscountPrice() {
        return this.price - this.price * this.discount / 100;
    }

    @JsonIgnore
    public List<Author> getAuthors() {
        return this.authorList.stream().map(AuthorBooks::getAuthor).collect(Collectors.toList());
    }

    @JsonIgnore
    public List<Genre> getGenres() {
        return this.genresList;
    }

    @JsonIgnore
    public List<Tag> getTags() {
        return this.tagsList;
    }

    public void setAuthors(List<Author> authorList) {
        int i = 1;
        for (Author author : authorList) {
            this.authorList.add(new AuthorBooks(this, author, i++));
        }
    }

    @JsonProperty("authors")
    public String getAuthorName() {
        if(this.getAuthorList().size() == 0)
            return null;
        this.getAuthorList().sort(Comparator.comparing(AuthorBooks::getSortIndex));
        return this.getAuthorList().get(0).getAuthor().getName() + (this.getAuthorList().size() > 1 ? " и др." : null);
    }

}