package com.example.MyBookShopApp.entity;

import com.fasterxml.jackson.annotation.JsonIgnore;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import javax.persistence.*;
import java.util.ArrayList;
import java.util.List;


@Getter
@Setter
@Entity
@NoArgsConstructor
@Table(name = "tags")
@ApiModel(description = "Data model of tag entity")
public class Tag {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @ApiModelProperty(value = "Tag id generated by DB", example = "1", required = true, position = 1)
    private Integer id;

    @Column(nullable = false)
    @ApiModelProperty(value = "Name of tag", example = "Romance", required = true, position = 2)
    private String name;

    @Column(nullable = false)
    @ApiModelProperty(value = "Slug of tag", example = "romance", required = true, position = 3)
    private String slug;

    @JsonIgnore
    @ManyToMany(mappedBy = "tagsList")
    private List<Book> books = new ArrayList<>();

    public Tag(String name, String slug) {
        this.name = name;
        this.slug = slug;
    }

}
